server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking
    username: ddtrinh
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: "NPSPm3Q7niAGJSryLpGq0j8bw21KehKKm7WgD+k1+BceNbt0noYIJR8DY8A1C7CR
gjMXpe3bu3OD02XcKiz25A=="
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

logging:
  level:
    org.hibernate.SQL: debug