spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking
    username: ddtrinh
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  server:
    port: 8080